# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Data schemas for expense reports, risk evaluations, and approval outcomes."""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class ExpenseReport(BaseModel):
    """Normalized expense report details."""

    amount: float = Field(..., description="Expense amount in USD")
    submitter: str = Field(..., description="Employee name or ID submitting the expense")
    category: str = Field(..., description="Expense category (e.g. Travel, Meals, Hardware, Software)")
    description: str = Field(..., description="Business purpose or item description")
    date: str = Field(..., description="Expense date (YYYY-MM-DD)")


class RiskAssessment(BaseModel):
    """Structured risk review output generated by the LLM."""

    risk_level: str = Field(
        ...,
        description="Assessed risk level: LOW, MEDIUM, or HIGH"
    )
    summary: str = Field(
        ...,
        description="Reasoning explaining the compliance and risk judgment"
    )
    flags: list[str] = Field(
        default_factory=list,
        description="Identified risk flags (e.g. 'Unusually high amount', 'Weekend transaction', 'Vague description')"
    )
    recommendation: str = Field(
        ...,
        description="Reviewer recommendation: APPROVE, REJECT, or FURTHER_INSPECTION"
    )


class ExpenseOutcome(BaseModel):
    """Final decision record for auditing and downstream systems."""

    status: str = Field(..., description="Final status: APPROVED, REJECTED, or PENDING")
    decision_type: str = Field(..., description="AUTO_APPROVED or HUMAN_DECISION")
    decision_by: str = Field(..., description="SYSTEM or HUMAN_APPROVER")
    expense: ExpenseReport
    risk_assessment: Optional[RiskAssessment] = None
    redacted_categories: list[str] = Field(
        default_factory=list,
        description="Categories of sensitive PII redacted from the expense description",
    )
    security_flagged: bool = Field(
        default=False,
        description="Whether a prompt injection attempt or security event was flagged",
    )
    notes: Optional[str] = None
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
